<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("races", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create races
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "races/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldTrack" class="col-sm-2 control-label">Track</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("track", "size" => 30, "class" => "form-control", "id" => "fieldTrack")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLaps" class="col-sm-2 control-label">Laps</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("laps", "size" => 30, "class" => "form-control", "id" => "fieldLaps")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDistance" class="col-sm-2 control-label">Distance</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("distance", "size" => 30, "class" => "form-control", "id" => "fieldDistance")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStart" class="col-sm-2 control-label">Start</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("start", "size" => 30, "class" => "form-control", "id" => "fieldStart")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnd" class="col-sm-2 control-label">End</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("end", "size" => 30, "class" => "form-control", "id" => "fieldEnd")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
