<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("raceweekends", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit raceweekends
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "raceweekends/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLocation" class="col-sm-2 control-label">Location</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("location", "size" => 30, "class" => "form-control", "id" => "fieldLocation")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStart" class="col-sm-2 control-label">Start</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("start", "size" => 30, "class" => "form-control", "id" => "fieldStart")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnd" class="col-sm-2 control-label">End</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("end", "size" => 30, "class" => "form-control", "id" => "fieldEnd")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSeriesId" class="col-sm-2 control-label">Series</label>
    <div class="col-sm-10">
        <?php
        echo $this->tag->select(
          array(
            "series_id",
            Series::find(array("order" => "name")),
            "using" => array("id" , "name"),
            "class" => "form-control",
            "id" => "fieldSeriesId"
          )
        );
        ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
