<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php $this->assets->outputJs() ?>
<?php $this->assets->outputCss() ?>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("series", "Go Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create series
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "series/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStart" class="col-sm-2 control-label">Start</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateTimeField(array("start", "size" => 30, "class" => "form-control", "id" => "fieldStart")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEnd" class="col-sm-2 control-label">End</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateTimeField(array("end", "size" => 30, "class" => "form-control", "id" => "fieldEnd")) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
<script type="text/javascript">
    $(function () {
        $('input[type=datetime]').datetimepicker({
            format: 'YYYY-MM-DD hh:mm:ss'
        });
    });
</script>
